services:
  postgres:
    image: postgres:15
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
  migrate-postgres:
    image: migrate/migrate:4
    command: ["-path=/migrations", "-database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - ./migrations/postgres:/migrations

networks:
  backend:

volumes:
  pg_data:
